### ISSUE TITLE
About Augmentation

### ISSUE THREAD

**Issue by CVHvn** [Bazinga699/NCL#2]
Hi friend, I see in table 4 you report result with RandAugment and without RandAugment (only use Horizontal flip and Random Crop). But in cifar100-LT config you set train transform is Horizontal flip and Random Crop. Can you achieve 53.31 (ensemble is 54.42) with train transform is Horizontal flip and Random Crop?

**Comment by Bazinga699** [comment]
The performance is 47.93(ensemble 49.22) without RandAugment, as shown in Table 4.
